/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface EawuIframeRootLink {
        "url": string;
    }
}
declare global {
    interface HTMLEawuIframeRootLinkElement extends Components.EawuIframeRootLink, HTMLStencilElement {
    }
    var HTMLEawuIframeRootLinkElement: {
        prototype: HTMLEawuIframeRootLinkElement;
        new (): HTMLEawuIframeRootLinkElement;
    };
    interface HTMLElementTagNameMap {
        "eawu-iframe-root-link": HTMLEawuIframeRootLinkElement;
    }
}
declare namespace LocalJSX {
    interface EawuIframeRootLink {
        "url"?: string;
    }
    interface IntrinsicElements {
        "eawu-iframe-root-link": EawuIframeRootLink;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "eawu-iframe-root-link": LocalJSX.EawuIframeRootLink & JSXBase.HTMLAttributes<HTMLEawuIframeRootLinkElement>;
        }
    }
}
